spring:
  application:
    name: library

  data:
    mongodb:
      uri: mongodb://34.64.109.220:50001/library

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


server:
  tomcat:
    connection-timeout: 1800000